import React from 'react';
import image from '../../images/banner.png'

const Blogs = () => {
    return (
        <div className='bg-cyan-900 py-10 text-slate-200'>
        <div className='grid grid-cols-1 w-11/12 mx-auto gap-20'>
            <div className='grid lg:grid-cols-2'><img className='lg:w-3/4' src={image} alt="" /><article><h1 className='text-2xl'>Q-1) How will you improve the performance of a React Application?</h1><p className='mt-5 text-lg'>By default react gives a fast UI. But some key factors play a good role to improve application performance. Such as <b>re-rendering a component when it happens</b>. Means we have to re-render a component when some activity occurs. <b>Using dynamic import</b> . Import() allows us to split big bundle of codes in small chunks. <b>Lazy loading</b> . By lazy loading we load images by preferences. This method improves page performance greatly.</p></article></div>
            <div className='grid lg:grid-cols-2'><article><h1 className='text-2xl'>Q-2) What are the different ways to manage a state in a React application?</h1><p>In a React application we can manage states in four ways. First one is local state. Local state is mostly used with useState. This helps us to toggle,change value dynamically etc. Secondly global state. When we want to change data all over the application or multiple components there we use global state. Another way is server state. We use server state when data that comes from an external server that must be integrated with our UI state. And finally the URL state. We use URL state when data that exists on our URLs, including the pathname and query parameters. These are the four types of state managements.</p></article><div className='flex justify-end'><img className='lg:w-3/4' src={image} alt="" /></div></div>
            <div className='grid lg:grid-cols-2'><img className='lg:w-3/4' src={image} alt="" /><article><h1 className='text-2xl'>Q-3) How does prototypical inheritance work?</h1><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo repellat dolores nisi doloremque magnam, in iste quibusdam similique amet pariatur totam vero, saepe soluta quas reprehenderit! Officia at iusto, id alias, eos esse non iure sint eveniet enim autem illo mollitia commodi expedita ad ipsa debitis magni cupiditate doloribus incidunt harum ex. Earum hic maxime, quos tenetur iusto esse fugiat!</p></article></div>
            <div className='grid lg:grid-cols-2'><article><h1 className='text-2xl'>Q-4) Why you do not set the state directly in React.</h1><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo repellat dolores nisi doloremque magnam, in iste quibusdam similique amet pariatur totam vero, saepe soluta quas reprehenderit! Officia at iusto, id alias, eos esse non iure sint eveniet enim autem illo mollitia commodi expedita ad ipsa debitis magni cupiditate doloribus incidunt harum ex. Earum hic maxime, quos tenetur iusto esse fugiat!</p></article><div className='flex justify-end'><img className='lg:w-3/4' src={image} alt="" /></div></div>
            <div className='grid lg:grid-cols-2'><img className='lg:w-3/4' src={image} alt="" /><article><h1 className='text-2xl'>Q-5) You have an array of products. Each product has a name, price, description, etc. How will you implement a search to find products by name?</h1><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo repellat dolores nisi doloremque magnam, in iste quibusdam similique amet pariatur totam vero, saepe soluta quas reprehenderit! Officia at iusto, id alias, eos esse non iure sint eveniet enim autem illo mollitia commodi expedita ad ipsa debitis magni cupiditate doloribus incidunt harum ex. Earum hic maxime, quos tenetur iusto esse fugiat!</p></article></div>
            <div className='grid lg:grid-cols-2'><article><h1 className='text-2xl'>Q-6) What is a unit test? Why should write unit tests?</h1><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo repellat dolores nisi doloremque magnam, in iste quibusdam similique amet pariatur totam vero, saepe soluta quas reprehenderit! Officia at iusto, id alias, eos esse non iure sint eveniet enim autem illo mollitia commodi expedita ad ipsa debitis magni cupiditate doloribus incidunt harum ex. Earum hic maxime, quos tenetur iusto esse fugiat!</p></article><div className='flex justify-end'><img className='lg:w-3/4' src={image} alt="" /></div></div>
        </div></div>
    );
};

export default Blogs;