import React from 'react';
import image from '../../images/banner.png'

const Blogs = () => {
    return (
        <div className='bg-cyan-900 py-10 text-white'>
        <div className='grid grid-cols-1 w-11/12 mx-auto gap-20'>
            <div className='grid lg:grid-cols-2'><img className='lg:w-3/4' src={image} alt="" /><article><h1 className='text-2xl'>Q-1) How will you improve the performance of a React Application?</h1><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo repellat dolores nisi doloremque magnam, in iste quibusdam similique amet pariatur totam vero, saepe soluta quas reprehenderit! Officia at iusto, id alias, eos esse non iure sint eveniet enim autem illo mollitia commodi expedita ad ipsa debitis magni cupiditate doloribus incidunt harum ex. Earum hic maxime, quos tenetur iusto esse fugiat!</p></article></div>
            <div className='grid lg:grid-cols-2'><article><h1 className='text-2xl'>Q-2) What are the different ways to manage a state in a React application?</h1><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo repellat dolores nisi doloremque magnam, in iste quibusdam similique amet pariatur totam vero, saepe soluta quas reprehenderit! Officia at iusto, id alias, eos esse non iure sint eveniet enim autem illo mollitia commodi expedita ad ipsa debitis magni cupiditate doloribus incidunt harum ex. Earum hic maxime, quos tenetur iusto esse fugiat!</p></article><div className='flex justify-end'><img className='lg:w-3/4' src={image} alt="" /></div></div>
            <div className='grid lg:grid-cols-2'><img className='lg:w-3/4' src={image} alt="" /><article><h1 className='text-2xl'>Q-3) How does prototypical inheritance work?</h1><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo repellat dolores nisi doloremque magnam, in iste quibusdam similique amet pariatur totam vero, saepe soluta quas reprehenderit! Officia at iusto, id alias, eos esse non iure sint eveniet enim autem illo mollitia commodi expedita ad ipsa debitis magni cupiditate doloribus incidunt harum ex. Earum hic maxime, quos tenetur iusto esse fugiat!</p></article></div>
            <div className='grid lg:grid-cols-2'><article><h1 className='text-2xl'>Q-4) Why you do not set the state directly in React.</h1><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo repellat dolores nisi doloremque magnam, in iste quibusdam similique amet pariatur totam vero, saepe soluta quas reprehenderit! Officia at iusto, id alias, eos esse non iure sint eveniet enim autem illo mollitia commodi expedita ad ipsa debitis magni cupiditate doloribus incidunt harum ex. Earum hic maxime, quos tenetur iusto esse fugiat!</p></article><div className='flex justify-end'><img className='lg:w-3/4' src={image} alt="" /></div></div>
            <div className='grid lg:grid-cols-2'><img className='lg:w-3/4' src={image} alt="" /><article><h1 className='text-2xl'>Q-5) You have an array of products. Each product has a name, price, description, etc. How will you implement a search to find products by name?</h1><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo repellat dolores nisi doloremque magnam, in iste quibusdam similique amet pariatur totam vero, saepe soluta quas reprehenderit! Officia at iusto, id alias, eos esse non iure sint eveniet enim autem illo mollitia commodi expedita ad ipsa debitis magni cupiditate doloribus incidunt harum ex. Earum hic maxime, quos tenetur iusto esse fugiat!</p></article></div>
            <div className='grid lg:grid-cols-2'><article><h1 className='text-2xl'>Q-6) What is a unit test? Why should write unit tests?</h1><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo repellat dolores nisi doloremque magnam, in iste quibusdam similique amet pariatur totam vero, saepe soluta quas reprehenderit! Officia at iusto, id alias, eos esse non iure sint eveniet enim autem illo mollitia commodi expedita ad ipsa debitis magni cupiditate doloribus incidunt harum ex. Earum hic maxime, quos tenetur iusto esse fugiat!</p></article><div className='flex justify-end'><img className='lg:w-3/4' src={image} alt="" /></div></div>
        </div></div>
    );
};

export default Blogs;