import React from 'react';
import image from '../../images/banner.png'

const Blogs = () => {
    return (
        <div className='bg-cyan-900 py-10 text-slate-200'>
        <div className='grid grid-cols-1 w-11/12 mx-auto gap-20'>
            <div className='grid lg:grid-cols-2'><img className='lg:w-3/4' src={image} alt="" /><article><h1 className='text-2xl'>Q-1) How will you improve the performance of a React Application?</h1><p className='mt-5 text-lg'>By default react gives a fast UI. But some key factors play a good role to improve application performance. Such as <b>re-rendering a component when it happens</b>. Means we have to re-render a component when some activity occurs. <b>Using dynamic import</b> . Import() allows us to split big bundle of codes in small chunks. <b>Lazy loading</b> . By lazy loading we load images by preferences. This method improves page performance greatly.</p></article></div>
            <div className='grid lg:grid-cols-2'><article><h1 className='text-2xl'>Q-2) What are the different ways to manage a state in a React application?</h1><p>In a React application we can manage states in four ways. First one is local state. Local state is mostly used with useState. This helps us to toggle,change value dynamically etc. Secondly global state. When we want to change data all over the application or multiple components there we use global state. Another way is server state. We use server state when data that comes from an external server that must be integrated with our UI state. And finally the URL state. We use URL state when data that exists on our URLs, including the pathname and query parameters. These are the four types of state managements.</p></article><div className='flex justify-end'><img className='lg:w-3/4' src={image} alt="" /></div></div>
            <div className='grid lg:grid-cols-2'><img className='lg:w-3/4' src={image} alt="" /><article><h1 className='text-2xl'>Q-3) How does prototypical inheritance work?</h1><p>Every object with its methods and properties contains an internal and hidden property known as Prototype. The Prototypal Inheritance is a feature in javascript used to add methods and properties in objects. It is a method by which an object can inherit the properties and methods of another object. Traditionally, in order to get and set the Prototype of an object, we use Object.getPrototypeOf and Object.setPrototypeOf. Nowadays, in modern language, it is being set using proto.</p></article></div>
            <div className='grid lg:grid-cols-2'><article><h1 className='text-2xl'>Q-4) Why you do not set the state directly in React.</h1><p>When we update a state by calling setState() it may replace the update we made. When we update a state directly it does not change state. Instead it creates a pending state transition.Sometimes there is high chance to loose control on all components because of setting the state directly. For these reasons we sould never update any state directly.</p></article><div className='flex justify-end'><img className='lg:w-3/4' src={image} alt="" /></div></div>
            {/* <div className='grid lg:grid-cols-2'><img className='lg:w-3/4' src={image} alt="" /><article><h1 className='text-2xl'>Q-5) You have an array of products. Each product has a name, price, description, etc. How will you implement a search to find products by name?</h1><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quo repellat dolores nisi doloremque magnam, in iste quibusdam similique amet pariatur totam vero, saepe soluta quas reprehenderit! Officia at iusto, id alias, eos esse non iure sint eveniet enim autem illo mollitia commodi expedita ad ipsa debitis magni cupiditate doloribus incidunt harum ex. Earum hic maxime, quos tenetur iusto esse fugiat!</p></article></div> */}
            <div className='grid lg:grid-cols-2'><img className='lg:w-3/4' src={image} alt="" /><article><h1 className='text-2xl'>Q-5) What is a unit test? Why should write unit tests?</h1><p>Unit tests are typically automated tests written and run by software developers to ensure that a section of an application (known as the "unit") meets its design and behaves as expected. In programming, a unit could be an entire module, but it is more commonly an individual function or procedure. In object-oriented programming, a unit is often an entire interface, such as a class, or an individual method. By writing tests first for the smallest testable units, then the compound behaviors between those, one can build up comprehensive tests for complex applications.</p></article></div>
        </div></div>
    );
};

export default Blogs;